mofied deploy steps

diff --git a/.github/workflows/backend-cd.yml b/.github/workflows/backend-cd.yml
--- a/.github/workflows/backend-cd.yml
+++ b/.github/workflows/backend-cd.yml
@@ -91,8 +91,9 @@ jobs:
         id: check_image
         run: |
           IMAGE_TAG="${{ secrets.AWS_ECR_REPOSITORY_BD }}:latest"
-          aws ecr describe-images --repository-name ${{ secrets.AWS_ECR_REPOSITORY_BD }} --image-ids imageTag=$IMAGE_TAG || echo "Image not found"
-        continue-on-error: true			  
+          IMAGE_EXISTS=$(aws ecr describe-images --repository-name ${{ secrets.AWS_ECR_REPOSITORY_BD }} --filters "tagStatus=TAGGED" "tagKey=latest" || echo "Image not found")
+          echo "Image exists: $IMAGE_EXISTS"
+          continue-on-error: true
       - name: Build Docker image
         if: steps.check_image.outcome == 'failure'	  
         run: |
diff --git a/.github/workflows/frontend-cd.yml b/.github/workflows/frontend-cd.yml
--- a/.github/workflows/frontend-cd.yml
+++ b/.github/workflows/frontend-cd.yml
@@ -79,8 +79,9 @@ jobs:
         id: check_image
         run: |
           IMAGE_TAG="${{ secrets.AWS_ECR_REPOSITORY }}:latest"
-          aws ecr describe-images --repository-name ${{ secrets.AWS_ECR_REPOSITORY }} --image-ids imageTag=$IMAGE_TAG || echo "Image not found"
-        continue-on-error: true		  
+          IMAGE_EXISTS=$(aws ecr describe-images --repository-name ${{ secrets.AWS_ECR_REPOSITORY }} --filters "tagStatus=TAGGED" "tagKey=latest" || echo "Image not found")
+          echo "Image exists: $IMAGE_EXISTS"
+          continue-on-error: true
       - name: Build Docker image
         if: steps.check_image.outcome == 'failure'
         run: |
